#! /usr/bin/perl
use strict;
sub total{
    # returns the total of a list of numbers.
    my $number;
    foreach (@_){
	$number+=$_;
    }
    $number;
}
my @fred=qw(1 3 5 7 9);
my $fred_total=total(@fred);
print "The total of \@fred is $fred_total.\n";
print "Enter some numbers on separate lines:\n";
my $user_total=total(<STDIN>);
print "The total of those numbers is $user_total.\n";
